/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\gun.glb m -o .\src\components\OptionHome\Dragon_Evolved.jsx -r public 
Author: Vlasov Daniil (https://sketchfab.com/dan741vlasov)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pistol-43-tactical-fps-animations-1a4c9d15818a4522aedbeb70919a17da
Title: Pistol 43 Tactical | FPS Animations
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function DragonEvolved({ hovered, ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/gun.glb')
  const { actions } = useAnimations(animations, group)
  console.log("actions",actions)
  useEffect(() => {
    const anim = hovered ? "Hands|Reloat_f" : "Hands|Inspect";
    actions[anim].reset().fadeIn(0.5).play();
    return () => actions[anim].fadeOut(0.5);
  }, [hovered]);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.016}>
          <group name="ab0012d711f24f669ab2e0234633e655fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Plane001" position={[0, 0, 3090.322]} rotation={[0, 0, -Math.PI / 4]} scale={[12.509, 180.576, 100]} />
                <group name="Hemi001" position={[5015.028, -5261.988, -0.002]} rotation={[0, 0, Math.PI]} scale={142.93}>
                  <group name="Object_6" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_7" />
                  </group>
                </group>
                <group name="Hands" rotation={[-Math.PI / 2, 0, 0]} scale={38.847}>
                  <group name="Object_9">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_97" rotation={[-Math.PI / 2, 0, 0]} scale={38.847} />
                    <group name="Object_100" position={[0, 68.418, -5.022]} rotation={[-Math.PI / 2, 0, 0]} scale={124.72} />
                    <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials['Tex_0011_1.dds']} skeleton={nodes.Object_98.skeleton} />
                    <skinnedMesh name="Object_99" geometry={nodes.Object_99.geometry} material={materials['Tex_0012_1.dds']} skeleton={nodes.Object_99.skeleton} />
                    <skinnedMesh name="Object_101" geometry={nodes.Object_101.geometry} material={materials.Glock_Mat} skeleton={nodes.Object_101.skeleton} />
                  </group>
                </group>
                <group name="BF3" rotation={[-Math.PI / 2, 0, 0]} scale={38.847} />
                <group name="Hemi" position={[-3808.78, 4619.217, 0]} rotation={[0, 0, 0.698]} scale={142.93}>
                  <group name="Object_104" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_105" />
                  </group>
                </group>
                <group name="Circle" scale={100} />
                <group name="Sphere" rotation={[0, Math.PI / 2, 0]} scale={100} />
                <group name="Light" position={[407.625, 590.386, -100.545]} rotation={[1.89, 0.881, -2.045]} scale={100}>
                  <group name="Object_109" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_110" />
                  </group>
                </group>
                <group name="Glock" position={[0, 68.418, -5.022]} rotation={[-Math.PI / 2, 0, 0]} scale={124.72} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/gun.glb')
