/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 .\public\models\cars\semi_scene.glb -o .\src\components\OptionHome\Fish.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Fish(props) {
  const { nodes, materials } = useGLTF('/models/cars/semi_scene.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.517, 1.811]} rotation={[-Math.PI / 2, 0, 0]} scale={0.721}>
        <group position={[0, 0, 0.21]}>
          <group position={[-1.044, 0.677, -0.669]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Tires_0.geometry} material={materials.Tire_Material} />
            <mesh geometry={nodes.Disks_0.geometry} material={materials['Black_material.001']} position={[-1.044, -0.677, 0.669]} />
            <mesh geometry={nodes.Disks001_0.geometry} material={materials.Disk_material} position={[-1.044, 3.314, 0.669]} />
            <mesh geometry={nodes.Disks002_0.geometry} material={materials.Disk_material} position={[-1.044, 2.385, 0.669]} />
          </group>
          <mesh geometry={nodes.Truck_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Truck_1.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Truck_2.geometry} material={materials.Lights} />
          <mesh geometry={nodes.Bumper_0.geometry} material={materials.Black_material} />
          <mesh geometry={nodes.Frame_0.geometry} material={materials.Black_material} />
          <mesh geometry={nodes.Handle_0.geometry} material={materials.TT_bake_node} position={[0, 3.833, -0.167]} rotation={[0, 0, -Math.PI]} />
          <mesh geometry={nodes.Plane_0.geometry} material={materials.Sign} />
          <mesh geometry={nodes.Plane001_0.geometry} material={materials.Black_material} />
          <mesh geometry={nodes.Tires002_0.geometry} material={materials.Tire_Material} position={[-1.044, 4.669, -0.669]} rotation={[0, 0, -Math.PI]} />
          <mesh geometry={nodes.Tires003_0.geometry} material={materials.Tire_Material} position={[-1.044, 3.74, -0.669]} rotation={[0, 0, -Math.PI]} />
          <mesh geometry={nodes.Tires004_0.geometry} material={materials.Tire_Material} position={[-1.044, 4.669, -0.669]} rotation={[0, 0, -Math.PI]} />
          <mesh geometry={nodes.Tires005_0.geometry} material={materials.Tire_Material} position={[-1.044, 3.74, -0.669]} rotation={[0, 0, -Math.PI]} />
        </group>
      </group>
      <group position={[4.272, -0.191, -2.576]} rotation={[0, -0.817, 0]} scale={0.874}>
        <mesh geometry={nodes.Wagon_Container.geometry} material={materials.White} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Wheels1.geometry} material={materials['Black.001']} position={[3.785, 0.227, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Wheels2.geometry} material={materials['Black.001']} position={[2.345, 0.227, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Wheels3.geometry} material={materials['Black.001']} position={[-2.262, 0.227, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.Wheels4.geometry} material={materials['Black.001']} position={[-3.702, 0.227, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
      <mesh geometry={nodes.Concrete_Barrier_Cube.geometry} material={materials.White} position={[-2.199, 0, -2.413]} rotation={[0, 0.669, 0]} />
      <mesh geometry={nodes.Cone_Cube001.geometry} material={materials.White} position={[-0.626, 0.027, -3.103]} rotation={[0, -0.109, 0]} />
      <mesh geometry={nodes.Cone_Cube002.geometry} material={materials.White} position={[-3.171, 0.027, -1.021]} rotation={[0, 0.321, 0]} />
    </group>
  )
}

useGLTF.preload('/models/cars/semi_scene.glb')
